/**
 * oma extension — multi-agent workflow layer.
 *
 * 1. Injects multi-agent workflow principles into the system prompt
 *    (via `before_agent_start`).
 * 2. Registers slash commands for the team pipeline:
 *    /team, /team-plan, /team-prd, /team-exec, /team-verify, /team-fix,
 *    /team-assemble, /intent, /status
 *
 * Ported from oh-my-iflow (oh-my-agent).
 */
import type { ExtensionAPI, ExtensionFactory } from "@earendil-works/pi-coding-agent";
import omaCore from "../prompts/oma-core.md" with { type: "text" };

// Placeholder replaced at runtime with the user's input.
const PH = "{{ARGS}}";

// ---------------------------------------------------------------------------
// Command prompts
// ---------------------------------------------------------------------------

const COMMAND_PROMPTS: Record<string, string> = {
	team: [
		"Coordinate the following request through the full team pipeline.",
		"",
		"Task:",
		PH,
		"",
		"Execution protocol (phased):",
		"1. **team-plan**: Delegate decomposition to `planner`, architecture-sensitive risks to `architect`. Build a phased task graph with owners and dependencies.",
		"2. **team-prd**: Delegate scoping and acceptance criteria to `product`.",
		"3. **team-exec**: Delegate implementation slices to `executor`.",
		"4. **team-verify**: Delegate verification to `reviewer` and `verifier`.",
		"5. **team-fix**: If verification fails, delegate root-cause analysis to `debugger` + patches to `executor`.",
		"6. Repeat steps 3–5 until acceptance criteria pass or a blocking issue is escalated.",
		"7. Return a merged lifecycle report.",
		"",
		"Final report format:",
		"## Pipeline Summary",
		"- Current phase:",
		"- Completion status:",
		"",
		"## Team Plan",
		"- ...",
		"",
		"## Phase Results",
		"- team-plan:",
		"- team-prd:",
		"- team-exec:",
		"- team-verify:",
		"- team-fix:",
		"",
		"## Completed Work",
		"- ...",
		"",
		"## Verification",
		"- ...",
		"",
		"## Open Items",
		"- ...",
	].join("\n"),

	"team-plan": [
		"Run team-plan phase.",
		"",
		"Task:",
		PH,
		"",
		"Protocol:",
		"1. Delegate decomposition to the `planner`.",
		"2. Delegate architecture-sensitive risks to the `architect`.",
		"3. Build a phased task graph with owners and dependencies.",
		"4. Tag tasks as sequential or parallelizable.",
		"5. Define verification checkpoints for each phase.",
		"",
		"Output format:",
		"## Phase",
		"- team-plan",
		"",
		"## Goals / Non-Goals",
		"- ...",
		"",
		"## Task Graph",
		"| Task | Owner | Dependencies | Parallel | Verification |",
		"|------|-------|-------------|----------|-------------|",
		"",
		"## Risks",
		"- ...",
		"",
		"## Ready for team-prd",
		"- ...",
	].join("\n"),

	"team-prd": [
		"Run team-prd phase.",
		"",
		"Task:",
		PH,
		"",
		"Protocol:",
		"1. Delegate scoping to the `product` agent.",
		"2. Convert user intent into measurable acceptance criteria.",
		"3. Define explicit non-goals to prevent scope creep.",
		"4. Document constraints (compatibility, timeline, dependencies, risk limits).",
		"5. Generate a handoff contract for team-exec and team-verify.",
		"",
		"Output format:",
		"## Phase",
		"- team-prd",
		"",
		"## Problem Statement",
		"- ...",
		"",
		"## Scope / Non-Goals",
		"- ...",
		"",
		"## Acceptance Criteria",
		"| Criterion | Required Evidence | Owner |",
		"|-----------|------------------|-------|",
		"",
		"## Constraints",
		"- ...",
		"",
		"## Handoff Contract",
		"- ...",
	].join("\n"),

	"team-exec": [
		"Run team-exec phase.",
		"",
		"Task:",
		PH,
		"",
		"Protocol:",
		"1. Confirm the currently accepted scope from team-prd.",
		"2. Delegate implementation to the `executor`.",
		"3. Keep each execution slice small and reviewable.",
		"4. Record changed files and rationale.",
		"5. Include checks/tests run for this slice.",
		"",
		"Output format:",
		"## Phase",
		"- team-exec",
		"",
		"## Scope Slice",
		"- ...",
		"",
		"## Implementation Log",
		"| Change | File | Reason |",
		"|--------|------|--------|",
		"",
		"## Verification Signals",
		"- ...",
		"",
		"## Ready for team-verify",
		"- ...",
	].join("\n"),

	"team-verify": [
		"Run team-verify phase.",
		"",
		"Task:",
		PH,
		"",
		"Protocol:",
		"1. Delegate code review to the `reviewer`.",
		"2. Delegate acceptance gate checks to the `verifier`.",
		"3. Verify each acceptance criterion with evidence.",
		"4. Classify issues as blocking, major, or minor.",
		"5. Generate a targeted fix list for team-fix.",
		"",
		"Output format:",
		"## Phase",
		"- team-verify",
		"",
		"## Acceptance Matrix",
		"| Criterion | Status (PASS/FAIL/UNKNOWN) | Evidence | Owner |",
		"|-----------|---------------------------|----------|-------|",
		"",
		"## Review Findings",
		"- ...",
		"",
		"## Fix List",
		"1. ...",
		"2. ...",
		"",
		"## Release Readiness",
		"- ...",
	].join("\n"),

	"team-fix": [
		"Run team-fix phase.",
		"",
		"Task:",
		PH,
		"",
		"Protocol:",
		"1. Consume the fix list from team-verify.",
		"2. Delegate root-cause analysis to the `debugger`.",
		"3. Delegate patches to the `executor` with minimal diffs.",
		"4. Confirm which issues are resolved and which remain open.",
		"5. Return an explicit handoff for the next team-verify round.",
		"",
		"Output format:",
		"## Phase",
		"- team-fix",
		"",
		"## Issues Processed",
		"| Issue | Root Cause | Fix | Status |",
		"|-------|-----------|-----|--------|",
		"",
		"## Remaining Issues",
		"- ...",
		"",
		"## Next Verification Scope",
		"- ...",
	].join("\n"),

	"team-assemble": [
		"Dynamically assemble a task-appropriate agent team, then execute.",
		"",
		"Task:",
		PH,
		"",
		"Protocol:",
		"1. Analyse the task shape:",
		"   - Domain (engineering / research / analysis / content / ops / mixed)",
		"   - Output goal (code / report / plan / demo)",
		"   - Risk and verification needs",
		"2. Assemble two role groups:",
		"   - Domain experts (problem-space specialists)",
		"   - Format experts (output-quality specialists)",
		"3. Map roles from available agents:",
		"   - Orchestration: `director`",
		"   - Exploration: `researcher` (spawn multiple when breadth is high)",
		"   - Decision: `consultant` or `architect`",
		"   - Execution: `executor` (when implementation is needed)",
		"   - Quality: `reviewer`, `verifier`, `debugger`",
		"   - Editing: `editor` (for final packaging)",
		"4. Define collaboration protocol:",
		"   - Explicit message flow between channels",
		"   - Verification/fix loop triggers",
		"   - Fallback paths when evidence conflicts or execution fails",
		"5. Present the proposed team and ask: 'Proceed with this team? (yes/no)'",
		"6. On approval, run: team-plan → team-prd → team-exec → team-verify → team-fix.",
		"7. Repeat team-exec → team-verify → team-fix until criteria pass or blocked.",
		"",
		"Output format:",
		"## Team Fitness Analysis",
		"- Task shape:",
		"- Required expertise:",
		"- Output goal:",
		"- Risk posture:",
		"",
		"## Proposed Team",
		"| Role | Agent | Why | Channel |",
		"|------|-------|-----|---------|",
		"",
		"## Collaboration Protocol",
		"- Handoff graph:",
		"- Verification/fix triggers:",
		"- Conflict resolution:",
		"",
		"## Approval Gate",
		"- Detected approval: yes/no",
		"",
		"## Execution Summary (on approval only)",
		"- Phase status:",
		"- Key results:",
		"- Open blockers:",
	].join("\n"),

	intent: [
		"Run intent gate to classify this request and route to the correct phase/command.",
		"",
		"Input:",
		PH,
		"",
		"Protocol:",
		"1. Classify the primary intent as one of:",
		"   - plan / prd / exec / verify / fix / research / lifecycle",
		"2. Identify missing constraints or acceptance criteria before execution.",
		"3. Detect command-intent mismatches (e.g., implementation request but missing planning phase).",
		"4. Recommend the next command and agent handoff.",
		"",
		"Routing hints:",
		"- Ambiguous scope → /team-plan",
		"- Scope ambiguity → /team-prd",
		"- Implementation ready → /team-exec",
		"- Verification request → /team-verify",
		"- Bug fix only → /team-fix",
		"- Option research → researcher agent",
		"- Full pipeline → /team",
		"",
		"Output format:",
		"## Intent Gate",
		"- Primary intent:",
		"- Confidence:",
		"- Command-intent mismatch: yes/no",
		"",
		"## Missing Inputs",
		"- ...",
		"",
		"## Recommended Route",
		"- Next command:",
		"- Delegate agent:",
		"",
		"## Ready-to-Run Prompt",
		"- ...",
	].join("\n"),

	status: [
		"Create a status report for the current project.",
		"",
		"User context:",
		PH,
		"",
		"Checklist:",
		"1. Check current repo status and changed files.",
		"2. Summarise work completed vs remaining, by pipeline phase (team-plan, team-prd, team-exec, team-verify, team-fix).",
		"3. Identify blocking issues and risk areas.",
		"4. Propose the next 1–3 concrete actions.",
		"",
		"Output format:",
		"## Snapshot",
		"- Pipeline phase:",
		"- Goal:",
		"- Progress:",
		"- Outstanding work:",
		"",
		"## Risks",
		"- ...",
		"",
		"## Next Actions",
		"1. ...",
		"2. ...",
		"3. ...",
	].join("\n"),
};

// ---------------------------------------------------------------------------
// Extension
// ---------------------------------------------------------------------------

const DESCRIPTIONS: Record<string, string> = {
	team: "Run the full team pipeline (plan → prd → exec → verify → fix)",
	"team-plan": "Phase 1/5: Build a phased plan with dependencies and verification checkpoints",
	"team-prd": "Phase 2/5: Lock scope with PRD-level acceptance criteria and constraints",
	"team-exec": "Phase 3/5: Implement approved plan slices with controlled scope",
	"team-verify": "Phase 4/5: Verify implementation against acceptance criteria",
	"team-fix": "Phase 5/5: Fix only verified issues, then prepare for re-verification",
	"team-assemble": "Dynamically assemble a task-appropriate agent team with approval gate",
	intent: "Classify task intent and route to the correct pipeline phase",
	status: "Summarise project status with risks and next actions",
};

export const omaExtension: ExtensionFactory = (pi: ExtensionAPI) => {
	// System prompt injection
	pi.on("before_agent_start", (event) => {
		const base = event.systemPrompt ?? "";
		return { systemPrompt: `${base}\n\n${omaCore}` };
	});

	// Register pipeline commands
	for (const [name, template] of Object.entries(COMMAND_PROMPTS)) {
		pi.registerCommand(name, {
			description: DESCRIPTIONS[name] ?? name,
			handler: async (args) => {
				const prompt = template.replaceAll(PH, args || "(no input provided)");
				pi.sendUserMessage(prompt);
			},
		});
	}
};
